float32[] action    # Action to take, [v, w]

---
float32[] state     # Next state as a result of the action taken
float32 reward      # Reward feedback 
bool done           # Flag to indicate if the episode is done
bool target         # Flag to indicate if goal is reached

